name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-build-release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install npm packages using cache
        uses: bahmutov/npm-install@v1
      - name: Copy example config
        run: cp .env.tmp .env.build
      - name: Lint code
        run: yarn lint
      - name: Lint docs
        run: yarn lint-docs
      # TODO: Add jest tests
      # - name: Run tests with coverage
      #   run: yarn cover
      - name: Build example project
        run: yarn build

      # at this point, the build is successful
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn semantic-release
